version: '3.9'
services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - 3000:3000
  #   platform: linux/x86_64
  #   working_dir: /app-frontend
  #   # depends_on:
  #   #   backend:
  #   #     condition: service_healthy
  #   healthcheck:
  #     test: ["CMD", "lsof", "-t", "-i:3000"] 
  #     timeout: 10s
  #     retries: 5
  # backend:
  #   build: ./backend
  #   ports:
  #     - 3001:3001
  #   platform: linux/x86_64
  #   working_dir: /app-backend
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   healthcheck:
  #     test: ["CMD", "lsof", "-t", "-i:3000"] 
  #     timeout: 10s
  #     retries: 5
  db:
    image: mongo:latest
    ports:
      - 3002:27017
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"] 
      timeout: 10s
      retries: 5
